### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by smooth-baking-powder** [stianaske/pybotvac#24]
Hi,

if i want to install pybotvac, i get this:

pip install pybotvac
```
pip install pybotvac
Collecting pybotvac
  Using cached https://files.pythonhosted.org/packages/2c/69/2c33e5abadad7571ccf21c702cc36cb21defb90314efcf20bd79d5572b34/pybotvac-0.0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BtvPPK/pybotvac/setup.py", line 2, in <module>
        from pybotvac import __version__
      File "pybotvac/__init__.py", line 1, in <module>
        from .account import Account
      File "pybotvac/account.py", line 5, in <module>
        import urllib.parse
    ImportError: No module named parse

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BtvPPK/pybotvac/

```

python setup.py install
 
```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from pybotvac import __version__
  File "/root/pybotvac/pybotvac/__init__.py", line 1, in <module>
    from .account import Account
  File "/root/pybotvac/pybotvac/account.py", line 5, in <module>
    import urllib.parse
ImportError: No module named parse
```

i installed requests:
 pip list
```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
ansible (2.6.4)
asn1crypto (0.24.0)
bcrypt (3.1.4)
certifi (2018.8.24)
cffi (1.11.5)
chardet (3.0.4)
chicken (0.1.0)
cryptography (2.3.1)
decorator (4.0.11)
egg (0.2.0)
enum34 (1.1.6)
feedparser (5.1.3)
gevent (1.3.6)
greenlet (0.4.15)
idna (2.7)
ipaddress (1.0.17)
Jinja2 (2.10)
keyring (10.1)
keyrings.alt (1.3)
MarkupSafe (1.0)
musicbrainzngs (0.6)
mutagen (1.36)
numpy (1.12.1)
paramiko (2.4.2)
pip (9.0.1)
pyasn1 (0.1.9)
pycparser (2.19)
pycrypto (2.6.1)
pygobject (3.22.0)
pyinotify (0.9.6)
PyNaCl (1.3.0)
pyOpenSSL (18.0.0)
python-dateutil (2.5.3)
pyxdg (0.25)
PyYAML (3.13)
quodlibet (3.7.1)
requests (2.19.1)
SecretStorage (2.3.1)
setuptools (40.4.3)
six (1.10.0)
urllib3 (1.23)
uTidylib (0.3)
version (0.1.1)
websocket (0.2.1)
wheel (0.29.0)
```

How can i fix it?

**Comment by stianaske** [comment]
This seems to have been an issue where urllib3 was imported using Python 3 style import. Release [v0.0.11](https://github.com/stianaske/pybotvac/releases/tag/v0.0.11) should resolve this.
