### ISSUE TITLE
Can't access to my neato Connected

### ISSUE THREAD

**Issue by jabesq** [stianaske/pybotvac#3]
Hi,

I just start to play with your API, but I can't use any robot method. There is no problem to retreive my robot throught my credentials, but when I want to run a robot method (ie: robot.get_current_state) I get the following error message

Traceback (most recent call last):
  File "sample/sample.py", line 13, in <module>
    print("State:\n", robot.state)
  File "/usr/local/lib/python3.4/dist-packages/pybotvac-0.0.1-py3.4.egg/pybotvac/robot.py", line 94, in state
    return self.get_robot_state().json()
  File "/usr/local/lib/python3.4/dist-packages/pybotvac-0.0.1-py3.4.egg/pybotvac/robot.py", line 70, in get_robot_state
    return self._message({'reqId': "1", 'cmd': "getRobotState"})
  File "/usr/local/lib/python3.4/dist-packages/pybotvac-0.0.1-py3.4.egg/pybotvac/robot.py", line 43, in _message
    headers=self._headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 298, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 500, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.4/dist-packages/pybotvac-0.0.1-py3.4.egg/pybotvac/robot.py", line 108, in __call__
    msg='\n'.join([self.serial.lower(), date, request.body]).encode('utf8'),
TypeError: sequence item 2: expected str instance, bytes found

**Comment by qelanhari** [comment]
Had the same issue, fixed it with this : 
`msg='\n'.join([self.serial.lower(), date, request.body.decode('utf8')]).encode('utf8')`
in robot.py

Did not search for another, maybe cleaner fix, since I didn't had the time to play more with the API.

**Comment by jabesq** [comment]
a bit better but I think the problem is coming from a change on Neato's server as I now have the following message:

rob.get_schedule()
<Response [200]>

rob.get_robot_state()
<Response [200]>

**Comment by qelanhari** [comment]
No, you may have another issue, I got proper response from neato.

**Comment by jabesq** [comment]
ok I got it get_robot_state do not return the state, we need to use the property state to get it:

> > > robot.state 
> > > {'availableCommands': {'resume': False, 'goToBase': False, 'stop': False, 'pause': False, 'start': True}, 'availableServices': {'houseCleaning': 'basic-1', 'manualCleaning': 'basic-1', 'schedule': 'basic-1', 'spotCleaning': 'basic-1', 'easyConnect': 'basic-1'}, 'meta': {'firmware': '2.0.0', 'modelName': 'BotVacConnected'}, 'data': {}, 'details': {'charge': 96, 'isDocked': True, 'isCharging': False, 'dockHasBeenSeen': False, 'isScheduleEnabled': False}, 'result': 'ok', 'error': 'ui_alert_invalid', 'action': 0, 'state': 1, 'cleaning': {'category': 2, 'mode': 2, 'spotWidth': 0, 'modifier': 1, 'spotHeight': 0}, 'reqId': '1', 'version': 1}

**Comment by qelanhari** [comment]
or self.get_robot_state().json()

**Comment by jabesq** [comment]
CLosing issue
