### ISSUE TITLE
sample.py issues

### ISSUE THREAD

**Issue by timppa1** [stianaske/pybotvac#4]
Has something changed in Neato side?? 

Running sample produces an error;

Robots:
Traceback (most recent call last):
  File "./sample.py", line 12, in <module>
    for robot in account.robots:
  File "/usr/lib/python2.6/site-packages/pybotvac-0.0.1-py2.6.egg/pybotvac/account.py", line 53, in robots
    self.refresh()
  File "/usr/lib/python2.6/site-packages/pybotvac-0.0.1-py2.6.egg/pybotvac/account.py", line 68, in refresh
    secret=robot['secret_key']))
  File "/usr/lib/python2.6/site-packages/pybotvac-0.0.1-py2.6.egg/pybotvac/robot.py", line 26, in **init**
    self._url = 'https://nucleo.neatocloud.com/vendors/neato/robots/{}/messages'.format(self.serial)
ValueError: zero length field name in format

**Comment by timppa1** [comment]
Seems to work with python 2.7.12 but not with 2.6.6
