### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by techwondr** [stianaske/pybotvac#5]
I keep getting ImportError: No module named requests when I attempt to run the sample.

`Zeus:sample Nick$ python sample.py 
Traceback (most recent call last):
  File "sample.py", line 1, in <module>
    from pybotvac import Account
  File "/Library/Python/2.7/site-packages/pybotvac-0.0.1-py2.7.egg/pybotvac/__init__.py", line 1, in <module>
    from .account import Account
  File "/Library/Python/2.7/site-packages/pybotvac-0.0.1-py2.7.egg/pybotvac/account.py", line 3, in <module>
    import requests
ImportError: No module named requests`

Any ideas?

**Comment by jeffch4n** [comment]
Have you installed the requests module?
I think you can install it directly with `pip install requests`, or from root directory `pip install -t requirements.txt`

**Comment by techwondr** [comment]
Wow, whoops. That did it - thanks for the quick response!
